development:
  host: mymaster
  role: master
  sentinels:
    -
      host: 127.0.0.1
      port: 26379
    -
      host: 127.0.0.1
      port: 26380
test:
  host: mymaster
  role: master
  sentinels:
    -
      host: 127.0.0.1
      port: 26379
    -
      host: 127.0.0.1
      port: 26380
